### ISSUE TITLE
Add *mavenLocal to default repositories?

### ISSUE THREAD

**Issue by breandan** [Kotlin/kotlin-jupyter#100]
When I first added a JSON dependency to a library published under Maven Local, the Kotlin Jupyter kernel was unable to resolve the dependency until I added `*mavenLocal` to the repositories section of the JSON manifest. Does it make sense to add `*mavenLocal` as a [default repository](https://github.com/Kotlin/kotlin-jupyter#default-repositories)?

Related to: #86

**Comment by ileasile** [comment]
It's easy to do, but I'm not sure it's needed, because it reduces reproducibility of notebooks, and we try to increase it.

**Comment by altavir** [comment]
In general, using mavenLocal as default is a bad practice since it produces strange errors when you have different artifacts with the same version on remote and on local. I do not think it is a problem in the Jupyter environment since it is fluid. But I still think it is easier to turn it on with annotation.
