### ISSUE TITLE
Support for custom type handlers

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/kotlin-jupyter#12]
E.g. in the sci-java kernel they have implemented type converters (such as https://github.com/scijava/scijava-jupyter-kernel/blob/master/src/main/java/ij/notebook/converter/ImagePlusToPNGNotebookConverter.java). 

I wonder if it would be possible to register those from within juptyer, to enable application domain handlers as needed. Something like
`registerTypeHandler(java.awt.image.BufferedImage.class, MyHandler())`

later just do 
`
BufferedImage(20, 10, BufferedImage.TYPE_INT_ARGB)
`
to render the object in the notebook.

So when starting a notebook users could pull in handlers as needed to visualizes domain specific class-instances (like images, tables, whatever).

**Comment by ligee** [comment]
Thanks for the good suggestion. If nobody will provide a PR for that, I'll do it during the next update round (should happen quite soon, I hope).

**Comment by altavir** [comment]
In the current implementation, the easiest way to implement custom renderers is to provide a definition for them in the module descriptor. You do not need to do anything else, no registration, etc. The only problem I found with that method is that you can't use interfaces for those render descriptors, only classes, because the notebook uses class name for resolution. I think that this problem could be solved by providing the `Renderable` interface inside of the notebook reflection artifact (see #88 )

cc @breandan

**Comment by breandan** [comment]
Thanks @altavir, I'll give it a try! I've also had some difficulty with the renderer specification. It would eventually be nice to support custom rendering based on an interface type. One hack to get this to work would be to define some kind of string matching procedure on `class.getInterfaces()` but agree it would be better to implement as a callback. #78

**Comment by ileasile** [comment]
Now there are two ways: you either implement `Renderable` or override `renderers` of `LibraryDefinition` in your integration class.
For more details see docs: https://github.com/Kotlin/kotlin-jupyter/blob/master/docs/libraries.md

**Comment by ileasile** [comment]
There are also type converters and annotation processors, see KDocs of api module for more info: https://github.com/Kotlin/kotlin-jupyter/blob/master/jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/LibraryDefinition.kt
