### ISSUE TITLE
%use kmath fails with "module not found"

### ISSUE THREAD

**Issue by bjonnh** [Kotlin/kotlin-jupyter#166]
````

:: problems summary ::
:::: WARNINGS
		module not found: kscience.kmath#kmath-commons;0.2.0

	==== jitpack.io: tried

	  https://jitpack.io/kscience/kmath/kmath-commons/0.2.0/kmath-commons-0.2.0.pom

	  -- artifact kscience.kmath#kmath-commons;0.2.0!kmath-commons.jar:

	  https://jitpack.io/kscience/kmath/kmath-commons/0.2.0/kmath-commons-0.2.0.jar
````
and a lot of others after that.

It ends with:
````
Failed to resolve kscience.kmath:kmath-commons:0.2.0:
File 'kscience.kmath:kmath-commons:0.2.0' not found
unresolved dependency: kscience.kmath#kmath-commons;0.2.0: not found
Failed to resolve kscience.kmath:kmath-for-real:0.2.0:
File 'kscience.kmath:kmath-for-real:0.2.0' not found
unresolved dependency: kscience.kmath#kmath-for-real;0.2.0: not found
````

Version of the kotlin-jupyter kernel is 0.8.3.122  (installed from anaconda)

**Comment by ileasile** [comment]
Hello, @bjonnh!
There are two problems. 
First of all, descriptor for kmath has been updated recently, so please update kernel to the latest (dev) version:
```
conda install -c jetbrains-dev kotlin-jupyter-kernel==0.8.3.293
```
Also, there is no 0.2.0 version of kmath: https://dl.bintray.com/mipt-npm/dev/kscience/kmath/kmath-core/
So, use either `0.2.0-dev-2` or `0.2.0-dev-5`. To do so, pass argument to `%use` magic:
```
%use kmath(0.2.0-dev-5)
```
cc @altavir

**Comment by altavir** [comment]
Both kmath and plotly descriptors seems to be out of date. We changed packages of all projects to `space.kmath`. I will fix it soon. Also, we will be focusing on the stand-alone descriptor modules using the new notebook API. 

Also due to a bug in the plugin, the mavenCentral version for 0.2.0 lacks the jars themselves. The repo.kotlin.link version is OK, but mavenCentral has a higher priority. I've recently re-deployed 0.2.1 to mavenCentral to fix that.

**Comment by bjonnh** [comment]
Perfect, thanks a lot to both of you.
